apiVersion: v1
kind: Service
metadata:
  name: vizier-core-rest
  namespace: kubeflow
  labels:
    app: vizier
    component: core-rest
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  rest_mapping
      prefix: /api/
      rewrite: /api/
      service: http://vizier-core-rest:80
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: api
  selector:
    app: vizier
    component: core-rest
