apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: katib-ui
  namespace: kubeflow
  labels:
    app: vizier
    component: ui
spec:
  replicas: 1
  template:
    metadata:
      name: katib-ui
      labels:
        app: vizier
        component: ui
    spec:
      serviceAccountName: katib-ui
      containers:
      - name: katib-ui
        image: katib/katib-ui
        command:
          - './katib-ui'
        ports:
        - name: ui
          containerPort: 80
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: katib-ui-nginx
  namespace: kubeflow
  labels:
    app: vizier
    component: ui-nginx
spec:
  replicas: 1
  template:
    metadata:
      name: katib-ui-nginx
      labels:
        app: vizier
        component: ui-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-static
        ports:
          - containerPort: 80
            protocol: TCP
      volumes:
      - name: nginx-static
        hostPath:
          path: /test
          type: Directory
